services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    Symfony\AI\Platform\PlatformInterface:
        alias: ai.platform.openai

    Symfony\AI\Platform\Bridge\OpenAi\Batch\JobClient:
        factory: ['Symfony\AI\Platform\Bridge\OpenAi\Factory', 'createJobClient']
        arguments: ['%env(OPENAI_API_KEY)%']
